version: '3'

services:
  api:
    image: strapi/strapi
    environment:
      - APP_NAME=gst-api
      - DATABASE_CLIENT=mongo
      - DATABASE_HOST=db
      - DATABASE_PORT=27017
      - DATABASE_NAME=gst
      - DATABASE_USERNAME=
      - DATABASE_PASSWORD=
      - HOST=localhost
    ports:
      - 1337:1337
    volumes:
      - ./gst-api:/usr/src/api/gst-api
      - /usr/src/api/gst-api/node_modules
    depends_on:
      - db
    restart: always

  db:
    image: mongo
    environment:
      - MONGO_INITDB_DATABASE=gst-api
    ports:
      - 27017:27017
    volumes:
      - ./db:/data/db
    restart: always
